### ISSUE TITLE
Docs pages not showing version in outdated version notice

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/doc.silverstripe.org#100]
self:setReminder() :  At three levels deep, the outdated version notice is not grabbing the version number being viewed. For instance, see

doc.silverstripe.org/en/3.1/developer_guides/model/how_tos/

**Comment by robbieaverill** [comment]
Doesn't appear to be a problem any more. Feel free to reopen if you find it again @SpiritLevel!
