### ISSUE TITLE
Links at http://open.silverstripe.org/ need updating

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/doc.silverstripe.org#101]
<b>framework issues</b> should point to https://github.com/silverstripe/silverstripe-framework/issues

<b>cms issues</b> should point to https://github.com/silverstripe/silverstripe-cms/issues

<b>modules</b> should point to http://addons.silverstripe.org/add-ons

<b>ticket reporting guidelines</b> should point to https://docs.silverstripe.org/en/contributing/issues_and_bugs

<b>code contributing guidelines</b> should point to https://docs.silverstripe.org/en/contributing/code

<b>documentation</b> should point to https://www.silverstripe.org/learn

<b>Roadmap</b> should point to https://github.com/silverstripe/silverstripe-framework/milestones and https://github.com/silverstripe/silverstripe-cms/milestones....or some sort of separate roadmap should be put together ?

**Comment by camfindlay** [comment]
Thats the old tracker system pre-github unlikely we'll be updating that site.

**Comment by SpiritLevel** [comment]
Yup....but there are only half a dozen or so links in all that need changing; small job I would have thought. It would be good to clean this up. What is involved ? I'll do it.

**Comment by camfindlay** [comment]
@chillu do you know the fate of open.silverstripe.org?

**Comment by chillu** [comment]
It's kind of handy to keep around for really old Trac ticket references in commits. I wouldn't be surprised if our operations teams shuts it down soon though, since its not actively maintained.

**Comment by SpiritLevel** [comment]
All the changelogs have references to open.silverstripe.org and these changelogs propagate all the way up to SS master. There are references to open.silverstripe.org elsewhere in the docs too....so the options seem to be:

(i) keep open.ss.org running, update the 8 or so links there, and keep the docs complete.
(ii) close down open.ss.org, and eliminate all references to it in the docs.
(iii) close down open.ss.org and decide how to redirect all the links to it.

Anything else will leave things untidy. Option (i)  is the least work and keeps the docs complete so is what I would prefer. Option (iii) is next best but involves a bit of work.

**Comment by chillu** [comment]
My vote is for (i), but eventually shut down open.ss.org. There's no point surfacing that URL anywhere to the community. It's main benefit is a few core committers digging up really old commits and requiring some context once every few months. Also, it's a great "blast from the past" resource, always makes me chuckle :D

**Comment by SpiritLevel** [comment]
So, (i) for the short term. Good. I'll update the open.ss.org links if someone can give me access :) Let's do this quickly if we can...

For the long term, would the preference be (ii) or (iii) ? Both involve a bit of work. I think it would be efficient to sort this out now while I am going through all the docs links...I can put these changes in a separate "shutdown open.ss.org" branch. Then, merge this branch in when the shutdown actually happens. What do you think ?

**Comment by camfindlay** [comment]
Happy to update.... raises the next question... who has access to this site @chillu? it's not one on my radar...

**Comment by SpiritLevel** [comment]
@camfindlay Excellent :) Just need to decide where "Roadmap" should point to.

Also, we need to decide on (ii) or (iii) so I can incorporate this into my current work on the links :)

Sorry for being pushy! But, as the saying goes, "strike while the iron is hot"....it will feel so good to have all this tidied up and out of the way. Besides, I have some things I want to get to over in addons and docsviewer and api and ..... :P

**Comment by tractorcow** [comment]
I don't... that's for sure.

**Comment by SpiritLevel** [comment]
?? Do elaborate....

**Comment by chillu** [comment]
@SpiritLevel Damian responded to a comment from me (who has access). Github doesn't show that in email notifications which probably placed the comment out of context for you.

@camfindlay Please talk to ops about access. Ask them to keep a database backup, otherwise the site can be shut down.

**Comment by SpiritLevel** [comment]
Thanks @chillu :) Will resume soon, after a couple of things are out of the way.

**Comment by SpiritLevel** [comment]
Bump....

**Comment by tractorcow** [comment]
I still can't do anything. ;P

@camfindlay are you handling this?

**Comment by camfindlay** [comment]
If I read this correctly... if I simply actioned the backup and shutdown of the site that would close this @tractorcow @chillu @SpiritLevel ?

**Comment by tractorcow** [comment]
Sure that'd be fine. ;)

**Comment by SpiritLevel** [comment]
@chillu seemed to want to keep the site up for the time being...option (i). I for either option (i) or (ii) :)

**Comment by camfindlay** [comment]
I'll lodge an ops ticket... @SpiritLevel this just made you job easier... 

@SpiritLevel @chillu earlier said.... and I quote "Please talk to ops about access. Ask them to keep a database backup, otherwise the site can be shut down."

**Comment by SpiritLevel** [comment]
@camfindlay Yay. It definitely simplifies my job! 

I am thinking that we should separate out the changelogs that refer to open.silverstripe.org. And, in these older changelogs, deactivate the links to open.silverstripe.org, while in the newer changelogs, there will be no references to open.silverstripe.org. In otherwords, for docs versions 3.1 and onwards, there will be no changelogs for 3.0 or 2.4. Do you agree with this approach ?

**Comment by camfindlay** [comment]
Not sure I quite get what you mean by... "here will be no changelogs for 3.0 or 2.4. " can you explain further...

**Comment by SpiritLevel** [comment]
Currently, all versions of the docs include links to changelogs for versions back to 2.0! 

I am suggesting that in versions 3.1 and up of the docs, all links to changelogs for versions earlier than 3.0 (or perhaps 3.1) be deleted. Alternatively, the links could be made inactive, but this would mean that urls with open.silverstripe.org will still be visible to the community. 

Bottom line: what do you want done with references to open.silverstripe.org ? And, do you want to have changelogs for version 2.0 appearing in the docs for version 4 ?

**Comment by camfindlay** [comment]
I'd want to keep the change log information but perhaps retire the links to individual tickets over on open.ss.org I think. Because we only have 1 stable currently version of docs at a time having all the change logs on each version is all good.

**Comment by SpiritLevel** [comment]
OK good :) I'll de-activate open.ss.org links and leave the information in place. Some other external links have no obvious replacement or update so I am just commenting those out too. 

Once I get my PR on docsviewer merged in, it would be nice to update the version of docsviewer being used live on doc.silverstripe.org so I can properly test all the api links. Can this be done fairly easily ?

**Comment by camfindlay** [comment]
Can you link me to your related PR please. I have a little time today to review.

**Comment by SpiritLevel** [comment]
Here we go:

https://github.com/silverstripe/silverstripe-docsviewer/pull/95

It is a minor change to what has already been merged but Dan seems to now be questioning the approach; I'll try to think of an improved algorithm.

**Comment by SpiritLevel** [comment]
See https://github.com/silverstripe/silverstripe-docsviewer/pull/94 for history.

**Comment by camfindlay** [comment]
Ops ticket has been lodged. Go forward assuming it'll close down at some point in the future.

**Comment by SpiritLevel** [comment]
Yay..... Thanks Cam.
