### ISSUE TITLE
.git folders removed from assets/src/framework_*

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/doc.silverstripe.org#115]
The function `RefreshMarkdownTask::cleanRepository()` removes the .git directories from each of the versions in `assets/src/`. This makes it very inconvenient to use the git workflow to contribute by editing markdown files. Also, having the full framework repos in `assets/src` means that one could also contribute to framework code from within docs. I suggest eliminating the `cleanRepository()` method altogether :)

**Comment by assertchris** [comment]
Hey! Thanks for contributing to this... :D

The reason we're removing everything but markdown files is because assets/src is publicly accessible. Leaving Git history and module PHP files is less secure than we'd like. @camfindlay just mentioned perhaps having a "dev" mode (disabled by default) which would leave these files in tact...

**Comment by SpiritLevel** [comment]
Howdy @assertchris ! 

Hmm...everything is already publicly readable on github. Is there really a security concern ? Or is there a particular reason forcing you to put the files in `assets` ?

I suppose, given `doc.silverstripe.org`'s unique structure, you could make assets not directly publicly accessible. Then, the "public" can only "access" the content after parsing by `docsviewer` (and `Parsedown`). However, simply by commenting out the line https://github.com/silverstripe/doc.silverstripe.org/blob/master/app/code/RefreshMarkdownTask.php#L115 after the composer command and before running the two sake tasks, you get everything anyways. This is what I did to keep the git repos ;)

Another alternative is to put the files somewhere else other than in `assets`. Perhaps leaving it in `src`, where is was before ? Or, maybe a folder called `markdown` ?  

Just my two cents worth!

**Comment by camfindlay** [comment]
There is a particular technical reason in our case why we've had to move the source to assets folder.

I'd be happy with a dev flag added to the build task that simply blocks the removal of all but the docs folder.

**Comment by SpiritLevel** [comment]
OK :) I'll have a look at putting a dev flag in.

**Comment by camfindlay** [comment]
could be as simple as a query string passed into the build task

**Comment by SpiritLevel** [comment]
See https://github.com/silverstripe/doc.silverstripe.org/pull/129
