### ISSUE TITLE
Potential for cloning a sparse subfolder of each source...

### ISSUE THREAD

**Issue by assertchris** [silverstripe/doc.silverstripe.org#118]
`git archive --remote=<repo_url> <branch> <path> | tar xvf -`

I'm not sure if this works with the `--depth`, `--branch`, and `--single-branch` flags of `git clone`.

**Comment by SpiritLevel** [comment]
Unless I read something incorrectly, it looks like `git archive` wouldn't keep the git history and hence wouldn't be any good for those that wanted to contribute (like me!).

**Comment by camfindlay** [comment]
Hence the mention of some sort of "dev" flag in those tasks

**Comment by SpiritLevel** [comment]
OK...I added a dev flag :)

**Comment by SpiritLevel** [comment]
See https://github.com/silverstripe/doc.silverstripe.org/pull/129

**Comment by camfindlay** [comment]
Perhaps have a crack at the sparse cloning to gain even more speedy task run :D

**Comment by SpiritLevel** [comment]
@camfindlay 

GitHub doesn't allow the use of `git archive`: https://twitter.com/GitHubHelp/status/322818593748303873

However, if subversion is running on docs.silverstripe.org, we could use this:

`svn export https://github.com/silverstripe/silverstripe-framework/branches/3.3/docs /local/folder/docs`

which only copies the docs folder and all of its contents from GitHub :) This would eliminating having to delete non-documentation files after a shallow clone. It works beautifully :)

There is no such thing as sparse cloning, only sparse checkout for which you still have to get the repository. We can't use git archive. Partial cloning by repo or shallow clones  are options but still bring down the repo and require deletion of files (currently we use shallow). See `http://www.peterlundgren.com/blog/on-gits-shortcomings/`. 

I'll submit a PR with the `svn export` command and you can decide if you like or not :)

**Comment by robbieaverill** [comment]
Triaging as an enhancement, we still have problems with how docsviewer downloads the source code (specifically how it deals with it on an NFS share)

**Comment by unclecheese** [comment]
Closing as resolved in rewrite of docs site. Can't say that this issue specifically is resolved, but the builds are faster, and Gatsby caches the cloned respositories.
