### ISSUE TITLE
Unable to search for anything with a '?' in the search term

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/doc.silverstripe.org#130]
See https://github.com/silverstripe/silverstripe-framework/issues/4007. The example given was searching for `?flush=1` but the same happens for any search with a question mark (haven’t tested other characters)

**Comment by camfindlay** [comment]
Cheers @kinglozzer - thinking it may be related to the Lucene search built into the docsvewier module.

**Comment by camfindlay** [comment]
Is this still an issue @kinglozzer ?

**Comment by dhensby** [comment]
@cam-findlay yep - https://docs.silverstripe.org/en/results/?q=%3Fflush&Versions=3.4&action_results=Search

**Comment by camfindlay** [comment]
Raise as a docsviewer bug referencing this looks related to inbuilt Lucene search.

**Comment by unclecheese** [comment]
Works on the new docs site.
