### ISSUE TITLE
Missing docs menu on tablet/mobile screen sizes, making navigation impossible

### ISSUE THREAD

**Issue by chillu** [silverstripe/doc.silverstripe.org#135]
I've noticed this by using doc.silverstripe.org on half of my desktop screen, as a reference next to an editor window. So this isn't a fringe use case of devs lookup up docs on their mobile, but I'd assume a fairly common case. This is different from the "screen resolution" tracked in Google Analytics, so we have no stats on how widespread this case is.

Since the menu is completely hidden, there's no way to navigate the docs in a structured way (other than clicking on random links).

![image](https://cloud.githubusercontent.com/assets/111025/15636365/e4eb8100-264f-11e6-8258-bcafbeec1422.png)

**Comment by camfindlay** [comment]
This is a feature/bug in the docsviewer module itself - will raise the issue there and @newleeland and I are looking into a PR for this.

**Comment by camfindlay** [comment]
Fixed in #143
