### ISSUE TITLE
Main menu doesn't display well on tablet/mobile

### ISSUE THREAD

**Issue by chillu** [silverstripe/doc.silverstripe.org#136]
This also covers devs who use docs as a reference in a small window (e.g. half the screen), so might be more widespread than initially thought.

![image](https://cloud.githubusercontent.com/assets/111025/15636377/31b812aa-2650-11e6-896a-8a47bb7da2f9.png)

See https://github.com/silverstripe/doc.silverstripe.org/issues/135 for missing docs menu

**Comment by camfindlay** [comment]
Fix in #143
