### ISSUE TITLE
Version checkbox in search results display broken

### ISSUE THREAD

**Issue by chillu** [silverstripe/doc.silverstripe.org#142]
https://docs.silverstripe.org/en/results/?q=theme&Versions=3.4&action_results=Search

![image](https://cloud.githubusercontent.com/assets/111025/18407546/a546a214-7767-11e6-92af-cb5c83d4caf2.png)

@newleeland Any chance you could have a look at that?

**Comment by camfindlay** [comment]
Broken or just poorly styled?

**Comment by camfindlay** [comment]
Now fixed
![screen shot 2016-10-28 at 10 02 55 am](https://cloud.githubusercontent.com/assets/367847/19787084/613f4a6a-9cfd-11e6-86f5-6addb1eef4f6.png)
