### ISSUE TITLE
Enhancement: CMS Configurable docs branches

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/doc.silverstripe.org#147]
In order to better maintain branches, it would be ideal to move from yml fixed config for docs configuration to CMS editable configuration.

* In the short term, we could have a RequestFilter which updated the Config api based on the data model.
* In the long term we could enhance docsviewer to accept non-config data sources.

**Comment by unclecheese** [comment]
Given the adoption of Gatsby as our site generator, this is no longer applicable.

**Comment by tractorcow** [comment]
I love gatsby good job.
