### ISSUE TITLE
Enhancement: Clone each branch from single source git repository

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/doc.silverstripe.org#148]
Instead of having a separate git repo for each branch which are individually pulled from the remote repo, it would be less overhead to have a single master repo which was updated periodically, and have individual branches `git clone` from this local repo.

Potentially: zero-downtime deployment if individual clones to temp directories, followed by rm and rename.

**Comment by unclecheese** [comment]
👍 This would speed up our Gatsby builds quite a bit.

**Comment by GuySartorelli** [comment]
I may be missing something here but there don't seem to be different repos for different branches? Closing.
