### ISSUE TITLE
Enhancement: Allow docs to be built from tags instead of branches

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/doc.silverstripe.org#150]
Useful for releasing docs for old versions that no longer have branches

**Comment by unclecheese** [comment]
At the moment, our source plugin `gatsby-source-git` does not allow a tag or sha as a reference -- only branch names. Would require a PR to that module, then adding a new instance of the git source to `gatsby-config.js` for the tag, and then updating our version switcher to be dynamic. Currently hardcoded as just 3 and 4 in the interest of getting the the MVP out.

**Comment by sminnee** [comment]
This is less relevant if we're not planning on hosting documentation specific to minor releases. If we're wanting to re-instate that, then it's pretty critical.

**Comment by GuySartorelli** [comment]
This isn't something we currently want to do.
