### ISSUE TITLE
Link colour too similar to text colour, can't see it's actually a link

### ISSUE THREAD

**Issue by chillu** [silverstripe/doc.silverstripe.org#155]
![image](https://cloud.githubusercontent.com/assets/111025/21154545/9ee80938-c1d3-11e6-827f-e1357bfc77bc.png)

Could we make it a darker shade of the SilverStripe blue maybe? @newleeland

**Comment by SpiritLevel** [comment]
bump 

As a regular reader of the documentation, this is quite an annoyance. It would be great to fix this.

**Comment by chillu** [comment]
@SpiritLevel Do you want to track down the line of CSS for this? I'm not sure if it's shared with other ss.org properties, but should be a simple fix for either of us, right? I'm too busy with 4.0 release, so have a good excuse ;)

**Comment by SpiritLevel** [comment]
I think @newleeland should fix it :P 

I'll take a look when I have a moment....

**Comment by robbieaverill** [comment]
Fixed with #166
