### ISSUE TITLE
Footer Misalignment

### ISSUE THREAD

**Issue by verydisco** [silverstripe/doc.silverstripe.org#158]
The footer seen in most pages is misaligned as seen here https://docs.silverstripe.org/en/4/getting_started/composer/#contributing

Padding should be removed from #footer and image's within the #footer div. Images should also be set as display block.

#footer, #footer img {padding: 0;}
#footer img {display: block;}

**Comment by robbieaverill** [comment]
Thanks @verydisco! With these changes we could also remove the `<br>` tag used for spacing around the CC image. Would you like to submit a pull request for this change?

**Comment by robbieaverill** [comment]
Fixed in https://github.com/silverstripe/silverstripe-docsviewer/pull/141, will be deployed soon

**Comment by dhensby** [comment]
raising zombies?

**Comment by sachajudd** [comment]
It's the lesser evil @dhensby. I aim to refix this in the coming weeks.
