### ISSUE TITLE
Adjust code block colours to be web accessible

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/doc.silverstripe.org#164]
Apologies to Ingo ( @chillu ) in advance :)

The low contrast syntax highlighting colors that Ingo switched the docs site to are a terrible strain on the eyes to read. I can't see how anyone would think the current color scheme is an improvement over the higher contrast code blocks (ie: black background, brightly colored text) that were there before. IMHO,  I think the color scheme should be returned to what it was. If you agree, please vote this issue up.

**Comment by chillu** [comment]
Thanks for calling this out David! :) I'll go with the guidance by our OSS designers here (pinging @newleeland and @clarkepaul). Context is here: https://github.com/silverstripe/silverstripe-docsviewer/pull/134

If this is mainly about contrast, that can be improved without going back to a black background - we can make the grey background a bit lighter? Definitely agree that readability is paramount for code examples. 

Before making this change, I looked around other OSS projects a bit. Everybody seems to rave about the quality of docs on Laravel, so I've went for a similar approach to presentation as well without thinking too deeply about it heh. Example: https://laravel.com/docs/5.4/blade

**Comment by SpiritLevel** [comment]
Hey @chillu 

I think the quality of Laravel docs people rave about is the content quality, not the visual presentation quality; I personally find the low contrast code blocks used in the Laravel docs are also a strain on the eyes to read :) Maybe its my advanced age...

I don't think lightening up the background will help much, and hence my suggestion of returning to a darker background, not necessarily black. But, alas, these are very personal preferences. It will be interesting to see how many people feel the same way as I do.  People: vote early and vote often!

Another related contrast issue is here: https://github.com/silverstripe/doc.silverstripe.org/issues/155

**Comment by robbieaverill** [comment]
We should be aiming for our docs to use accessible (WCAG) colours, personally I'd be in favour of making the text darker rather than switching back to an inverted colour scheme. Cc @sachajudd

**Comment by SpiritLevel** [comment]
My first preference would be dark background with bright text. As a second preference, darken the text as @robbieaverill suggests...something has to be done to increase the contrast! :)

**Comment by clarkepaul** [comment]
FYI I've added this to our design backlog but if someone wants to sort this prior to us looking into it please do so, as it might take a bit time for us to get around to it.
