### ISSUE TITLE
Layout issue for images

### ISSUE THREAD

**Issue by k8i80** [silverstripe/doc.silverstripe.org#171]
just noticed this on SilverStripe docs on a couple of pages.
Images look fine on mb and tablet but on desktop there is an overlap issue. Might be worth checking on the rest of the docs pages if similar layout. 

https://docs.silverstripe.org/en/4/developer_guides/files/file_management/
https://docs.silverstripe.org/en/4/developer_guides/files/images/

**Comment by robbieaverill** [comment]
Nasty! Looks like there's a `float: right` being inherited from somewhere. Do you feel like making a pull request @k8i80?

**Comment by chillu** [comment]
Just hit that as well :(

**Comment by robbieaverill** [comment]
Will be deployed shortly with #172
