### ISSUE TITLE
Docs don't filter by version as expected

### ISSUE THREAD

**Issue by micmania1** [silverstripe/doc.silverstripe.org#174]
![image](https://user-images.githubusercontent.com/881537/37126340-6aae4be6-22d5-11e8-85e2-dbb80fc4bca1.png)

When I search the docs, ticking version 4 only, I see results for all versions of SilverStripe. I'd expect only to see results for version 4.

**Comment by micmania1** [comment]
For context; I'm current running dev training and I wanted the trainee to find the results themselves. Its really hard to find SS4 docs for UploadField using the search and google only takes you to the SS3 docs. We ended up using SS3 docs.

**Comment by unclecheese** [comment]
The new Algolia based search will filter by version, but currently SS3 search is broken https://github.com/silverstripe/doc.silverstripe.org/issues/196

Closing as fixed and new bugs already tracked.
