### ISSUE TITLE
Pull SS3 docs from 3.7 branch while retaining `3` URLs

### ISSUE THREAD

**Issue by sminnee** [silverstripe/doc.silverstripe.org#179]
At some stage in the near future, we're likely to delete the `3` branch, once we stop producing new minor releases.

After that point, the documentation hosted at https://docs.silverstripe.org/en/3/ will need to be pulled from the 3.7 branch instead of the 3 branch.

We don't want to break the URLs either.

**Comment by tractorcow** [comment]
At this point, we may as well change from "branch based docs" to "tag based docs".

I would like the "3" docs to point to "latest 3.x tag". That's something we could do now in anticipation of deleting 3 branch, meaning that once we remove it, the docs don't break.

**Comment by dhensby** [comment]
would that mean not publishing the dev docs at all for any branch?

**Comment by tractorcow** [comment]
Yes that's right. Dev docs could still be found on github.

**Comment by sminnee** [comment]
I don't think tag-based docs are a good idea, as it will further slow down the turnaround time on docs updates.

Also it would confusing to have half the docs be branch based and half the docs be tag based.

**Comment by tractorcow** [comment]
Ok fair enough.

**Comment by unclecheese** [comment]
This is a one-liner in the new Gatsby set up. https://github.com/silverstripe/doc.silverstripe.org/pull/202
