### ISSUE TITLE
BUG Errors with user defined session save handler

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/doc.silverstripe.org#182]
See https://app.raygun.com/crashreporting/yzpho6/errors/2940703152?correlationId=40476426488&occurredOn=2018-11-26T14:05:20.0000000Z#36952845833

* docs.silverstripe.org - error still occurring 1 minute later - Error: session_write_close(): Failed to write session data using user defined save handler. (session.save_path: /var/lib/php/sessions)

Could be related to https://github.com/silverstripe/silverstripe-hybridsessions/issues/43

**Comment by robbieaverill** [comment]
Still happening

**Comment by unclecheese** [comment]
Static site now. No more sessions!
