### ISSUE TITLE
Global search in toolbar is broken

### ISSUE THREAD

**Issue by chillu** [silverstripe/doc.silverstripe.org#184]
The search icon on the top right doesn't work on docs.ss.org or api.ss.org.

This is due to a commit by @emteknetnz with `X-Frame-Options` being introduced on ss.org: https://github.com/silverstripeltd/silverstripe.org/commit/92bba9edc5eafe43e3b852802a907a8e39522560#diff-8052c42ab3b8aa06a3f5f788a4ddccc2

**Comment by unclecheese** [comment]
Not using global toolbar anymore.
