### ISSUE TITLE
RFC: New docs site

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/doc.silverstripe.org#193]
I've been working on rebuilding the docs site in Gatsby. Here is a preview, deployed to Netlify.

https://ss-docs-gatsby.netlify.com/

Please provide any feedback here. 

Documentation on how this affects our processes to follow, but right now just trying to squash any major issues.

**Comment by madmatt** [comment]
What is fobo.com and why do I get taken there when I click 3.x in the version dropdown?

**Comment by unclecheese** [comment]
Right, so should mention that version switching doesn't work yet. Hoping to get the 3x by later this week. Looks like the test data I had in my local `.env.production` file is overriding the environment variables on netlify. So that should be fixed in the commit I just pushed up.

**Comment by robbieaverill** [comment]
Looking good @unclecheese, awesome work! 

Couple of quick things I noticed:

* Every code block has a space at the start of the snippet
* Nice work getting the API shortcode stuff working
* Unfortunately still suffers from unrendered markdown in "notice" divs, example "Installing composer" on https://ss-docs-gatsby.netlify.com/getting_started/composer/
* https://ss-docs-gatsby.netlify.com/developer_guides/extending/how_tos/ is 404 - is something custom?
* Would be cool to have the "Edit this page on GitHub" button at the bottom somewhere, as well as the license info
* I miss being able to click on a heading and have it anchor to it - can we add that back?
* Tables could use some styles e.g. 100% width and maybe alternating row backgrounds - example PHP requirements on https://ss-docs-gatsby.netlify.com/getting_started/server_requirements/
* The sub-navigation under "Controllers" doesn't render as nested when you first load https://ss-docs-gatsby.netlify.com/developer_guides/controllers/. If you click on "Introduction to a Controller" then it does

I can't wait to see this happen!

**Comment by unclecheese** [comment]
Thanks, Robbie!

* Every code block has a space at the start of the snippet

--> Just noticed this myself. Thanks.

* Unfortunately still suffers from unrendered markdown in "notice" divs, example "Installing composer" on https://ss-docs-gatsby.netlify.com/getting_started/composer/

--> Tracking this. It's annoying that the markdown parser stops when it sees the `div` tag. I understand why, but it's weird that it allows things like unordered lists. Working on a hack for this today. A particularly insidious side-effect is that `<%` kills the build because React tries to parse it as an HTML tag. So those have to be escaped.

* https://ss-docs-gatsby.netlify.com/developer_guides/extending/how_tos/ is 404 - is something custom?

--> Just noticed this. Should be excluded or better yet we should just put index.md files in them.

* Would be cool to have the "Edit this page on GitHub" button at the bottom somewhere, as well as the license info

---> Love it

* I miss being able to click on a heading and have it anchor to it - can we add that back?

--> Tracking this.. we need to do the `{#my-identifier}` parsing.

*

* Tables could use some styles e.g. 100% width and maybe alternating row backgrounds - example PHP requirements on https://ss-docs-gatsby.netlify.com/getting_started/server_requirements/

---> Nice one, thank you.

* The sub-navigation under "Controllers" doesn't render as nested when you first load https://ss-docs-gatsby.netlify.com/developer_guides/controllers/. If you click on "Introduction to a Controller" then it does


---> Interesting. Will look.

**Comment by bergice** [comment]
The sidebar scrolls all the way back up whenever you navigate anywhere.

**Comment by unclecheese** [comment]
Interesting. I agree it's not great, but isn't that status quo? A server rendered app would do that too.

**Comment by unclecheese** [comment]
> Some of the pages look a bit barebones compared to the original. For example https://ss-docs-gatsby.netlify.com/lessons/ vs https://www.silverstripe.org/learn/lessons/v4/

This is a comparison between the lessons page on .org versus the docs page? The two docs pages look similar to me.

**Comment by bergice** [comment]
> Interesting. I agree it's not great, but isn't that status quo? A server rendered app would do that too.

It's not very user friendly.

> This is a comparison between the lessons page on .org versus the docs page? The two docs pages look similar to me.

The content is the same. But I feel like it's missing some sort of header or an introduction paragraph.

And the bullet links could use some descriptions too, like they do in the original. Not sure how much work that would be to get working.

**Comment by unclecheese** [comment]
> It's not very user friendly.

You're right. Thanks for flagging this. Took a bit of effort, but I figured out why it was doing that and it identified a flaw in the way the component was built.

**Comment by unclecheese** [comment]
- [ ] Every code block has a space at the start of the snippet

- [ ] Unfortunately still suffers from unrendered markdown in "notice" divs, example "Installing composer" on https://ss-docs-gatsby.netlify.com/getting_started/composer/

- [x] https://ss-docs-gatsby.netlify.com/developer_guides/extending/how_tos/ is 404 - is something custom?

- [x] Would be cool to have the "Edit this page on GitHub" button at the bottom somewhere

- [ ] as well as the license info

- [x] I miss being able to click on a heading and have it anchor to it - can we add that back?

- [x] Tables could use some styles e.g. 100% width and maybe alternating row backgrounds - example PHP requirements on https://ss-docs-gatsby.netlify.com/getting_started/server_requirements/

- [x] The sub-navigation under "Controllers" doesn't render as nested when you first load https://ss-docs-gatsby.netlify.com/developer_guides/controllers/. If you click on "Introduction to a Controller" then it does
- [x] The sidebar scrolls all the way back up whenever you navigate anywhere.

**Comment by chillu** [comment]
AMAZING! Left some peer review feedback on https://github.com/silverstripe/doc.silverstripe.org/pull/194

The mobile layout has a lot of padding. Something for after go-live.

![image](https://user-images.githubusercontent.com/111025/68627260-3a297f80-0542-11ea-9d15-1f971adf1664.png)

**Comment by DorsetDigital** [comment]
Possibly related to a previous issue, but the API links don't seem to convert properly when in a list:

https://ss-docs.netlify.com/en/4/developer_guides/files/file_storage/

![Screenshot from 2019-11-14 08-27-18](https://user-images.githubusercontent.com/15108750/68839451-a4fcc700-06b8-11ea-8641-76f9375bfaa4.png)

**Comment by DorsetDigital** [comment]
Sorry, should probably have waited and posted these at once:

- UI feedback:  The scrollbar on the left-nav is very thin.  It probably looks nicer, but I've found it makes it a real PITA to grab if you want to scroll the panel
- Search doesn't seem to work.   Common searches such as 'gridfield', 'image' return nothing.
- On a small screen, there seems to be a formatting issue with long language text.  (See https://ss-docs.netlify.com/en/4/developer_guides/email/) and attached file.   The long text expands out to the right.  On this page, the code examples are being truncated too.
![ss-docs netlify com_en_4_developer_guides_email__(iPhone 6_7_8)](https://user-images.githubusercontent.com/15108750/68840467-b5ae3c80-06ba-11ea-8b74-21aeda4e5479.png)

- Not sure if it's specific to the current platform, but I'm seeing a load of 404 errors on page load looking for page-data.json  (https://ss-docs.netlify.com/page-data/en/4/controllers/routing/page-data.json)

**Comment by kinglozzer** [comment]
> Please provide any feedback here.

It’s fast and sexy 🔥

**Comment by unclecheese** [comment]
Thanks, @DorsetDigital 
* Have fixed the API links
* Should have mentioned search isn't working yet, but Algolia finally indexed it and we're good now.
* `page-data.json` issues seem to be caching old pages. Will rebuild with a flush.
* Formatting issue doesn't seem easy to solve at the moment. I'm not sure it's a huge blocker, but thanks for the heads up.

**Comment by unclecheese** [comment]
Site is now live. Thanks, everyone.
