### ISSUE TITLE
Search results direct to netlify

### ISSUE THREAD

**Issue by DorsetDigital** [silverstripe/doc.silverstripe.org#197]
I'm guessing this is just an indexing / caching problem, but currently the search results point at the netlify domain:

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/15108750/68933868-78ff4580-078d-11ea-9340-a11ad6cb9543.gif)

**Comment by unclecheese** [comment]
Should be fixed by this merge: https://github.com/algolia/docsearch-configs/pull/1118

**Comment by DorsetDigital** [comment]
Yep, it appears to be working as expected now.  Can probably close this.
