### ISSUE TITLE
Code font size is bigger than content font size

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/doc.silverstripe.org#198]
Not sure if this is just my browser but I'm finding it a little weird to read the content between code samples. I would agree that code samples are probably the most useful bits of information on the screen but having a consistent font would probably be easier on the eyes

~Also, as the Gatsby rebuild is live can we please put it in `master`?~ See #199

**Comment by unclecheese** [comment]
Have decreased the font size. Please review and close if resolved.

**Comment by ScopeyNZ** [comment]
❤️
