### ISSUE TITLE
Merge the Gatsby branch

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/doc.silverstripe.org#199]
As this appears to be live now can we please merge the branch into `master`?

**Comment by ScopeyNZ** [comment]
@unclecheese I think this is done now but the Gatsby branch is still around? Should that be deleted and should this issue be closed?

**Comment by unclecheese** [comment]
Can be now. I didn’t delete it because I wanted to ensure the netlify build didn’t break. But it looks like it’s running fine off the master branch now so we’re good.

**Comment by unclecheese** [comment]
Have deleted the PR branch
