### ISSUE TITLE
Navbar visual improvements

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/doc.silverstripe.org#201]
Side navigation should begin directly under the header toolbar for docs. Remove the white space which causes navigation items to get cut off when scrolling. We still need enough space at the top but apply in within the scroll area rather than above it.
<img width="237" alt="Pasted_Image_18_11_19__4_21_PM" src="https://user-images.githubusercontent.com/555033/69022401-12458a80-0a20-11ea-9c0e-50ade1d50a96.png">

At the bottom of the navigation menu, we should additional space at the bottom.
<img width="218" alt="Pasted_Image_18_11_19__4_24_PM" src="https://user-images.githubusercontent.com/555033/69022398-0e196d00-0a20-11ea-8066-2dc74c9dbaeb.png">

**Comment by unclecheese** [comment]
Have revised in latest deploy. Please review and close if resolved.
