### ISSUE TITLE
Anchor links no longer work

### ISSUE THREAD

**Issue by madmatt** [silverstripe/doc.silverstripe.org#204]
Not sure if this is intentional or not, but we have lots of comments in code, as well as discussions etc that deep-link to a specific part of the documentation, identified by heading. The old docs site added an `<a id="abc123">` for each `<hX>` tag in the doc, but the new site doesn't do this. Is it possible to re-instate.

Example link: https://docs.silverstripe.org/en/4/developer_guides/debugging/error_handling/#raising-errors-and-logging-diagnostic-information
See example link in context here: https://docs.platform.silverstripe.com/platform-features/logs/#logging-custom-events-in-silverstripe-4-x (the link text is "this guide", under the YML config block).

**Comment by unclecheese** [comment]
Fixed in latest deploy.

**Comment by unclecheese** [comment]
@madmatt Can you please have a look and close if resolved?

**Comment by madmatt** [comment]
Looks good to me, thanks @unclecheese!
