### ISSUE TITLE
Cards with icons layout improvements

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/doc.silverstripe.org#206]
Just some quick CSS changes to improve the presentation of icons in cards required.
Is currently:
![image](https://user-images.githubusercontent.com/555033/69114579-aed45f00-0aea-11ea-9d86-21f20512d0d0.png)

Should look more like:
<img width="447" alt="Pasted_Image_19_11_19__4_31_PM" src="https://user-images.githubusercontent.com/555033/69114478-61f08880-0aea-11ea-85ba-ff2c9da93418.png">

**Comment by unclecheese** [comment]
Have revised in latest deploy, and have gotten approval from @clarkepaul outside this thread.
