### ISSUE TITLE
URLs without a version do not redirect to the latest stable

### ISSUE THREAD

**Issue by indygriffiths** [silverstripe/doc.silverstripe.org#212]
Previously you could visit a page like https://docs.silverstripe.org/en/getting_started/environment_management/ and have it redirect automatically to https://docs.silverstripe.org/en/4/getting_started/environment_management/, but this seems to no longer happen and has broken some links in the Cloud Platform docs. 

Unsure if you'd consider it a bug or not so filing anyway.

**Comment by dnsl48** [comment]
Well, that's a regression if it used to work. Regressions should be handled as bugs, although I'm not sure about the impact for this particular one.

**Comment by michalkleiner** [comment]
Impact is high if ss.org links to the version-less URLs.

**Comment by GuySartorelli** [comment]
This was fixed at some stage - works now.
