### ISSUE TITLE
Get anchor permalinks

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/doc.silverstripe.org#213]
## Overview
It looks like #204 reinstated the possibility of anchoring a heading by manually appending the URL to reference the heading, but it would be great if headings had an anchor permalink icon to either:
* redirect the user's URL to the anchor - so it can be copied and shared elsewhere; or
* copy the permalink of the anchor to the user's clipboard

I _believe_ this was functionality present in the old docs site. Regards, it's a pretty handy tool!

**Comment by unclecheese** [comment]
Resolved by https://github.com/silverstripe/doc.silverstripe.org/pull/219
