### ISSUE TITLE
In-line code blocks in headers stop rendering

### ISSUE THREAD

**Issue by madmatt** [silverstripe/doc.silverstripe.org#215]
For example, compare the first sub-heading under "Step 1" of the upgrade guide:

Source: https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/03_Upgrading/01_Upgrading_project.md#automatically-upgrade-dependencies-with-the-recompose-upgrader-command

Rendered: https://docs.silverstripe.org/en/4/upgrading/upgrading_project/#step1

The rendered view seems to get cut off at the `in-line code block`:

![Upgrading_to_SilverStripe_4___Silverstripe_CMS_Documentation](https://user-images.githubusercontent.com/893117/70482299-03975280-1b4a-11ea-9f54-4311e3c6ae6f.png)

## PRs
- https://github.com/silverstripe/doc.silverstripe.org/pull/241

**Comment by robbieaverill** [comment]
I've triaged this assuming that it's easiest to replace the backticks with double quotes to get it working again

**Comment by madmatt** [comment]
Note that there are many places where this is done - there are multiple just on this one page of documentation, I haven't undertaken an exhaustive search.
