### ISSUE TITLE
Pages missing from [CHILDREN] list

### ISSUE THREAD

**Issue by madmatt** [silverstripe/doc.silverstripe.org#217]
I don't know if this is intentional or not.

On this page: https://docs.silverstripe.org/en/4/developer_guides/integration/

In the side menu there are three pages, but on the page itself it only shows two pages (missing the 'How-tos' page).

**Comment by GuySartorelli** [comment]
how tos is a folder, so it would need `includefolders` in the `[CHILDREN]` block to include it - but looking around there are many sections like that, with "how tos" in the left menu but not in the children block. Gonna call this a feature and not a bug.
