### ISSUE TITLE
Top google search result goes to v3

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/doc.silverstripe.org#221]
When I google search for "install silverstripe" the top result points to 
https://docs.silverstripe.org/en/3/getting_started/installation/

Seems like we might want to put a noindex on the /en/3/ pages otherwise we'll just confuse people who are new to silverstripe

**Comment by robbieaverill** [comment]
We used to have a canonical link to 4 but it may have been lost during the rebuild, also it may have had some issues with the search integration at the time and been removed

**Comment by unclecheese** [comment]
Pull request: https://github.com/silverstripe/doc.silverstripe.org/pull/227/files
