### ISSUE TITLE
ONGOING: replace forks in sources-user.js file

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/doc.silverstripe.org#223]
We've had to rely on changes to thirdparty modules to make the userhelp site work, and we couldn't wait on merges, so we're still sourcing from several forks. As these PRs get merged, tick off the boxes. When complete, close this issue.

### versionedfiles

* [x] https://github.com/symbiote/silverstripe-versionedfiles/pull/66
* [x] https://github.com/symbiote/silverstripe-versionedfiles/pull/67

### advancedworkflow

* [x] https://github.com/symbiote/silverstripe-advancedworkflow/pull/415
* [x] https://github.com/symbiote/silverstripe-advancedworkflow/pull/414
* [x] https://github.com/symbiote/silverstripe-advancedworkflow/pull/413

### forum
* [x] https://github.com/silverstripe-archive/silverstripe-forum/pull/213
* [x] https://github.com/silverstripe-archive/silverstripe-forum/pull/211

### maintenance
* [x] https://github.com/bringyourownideas/silverstripe-maintenance/pull/141
* [x] https://github.com/bringyourownideas/silverstripe-maintenance/pull/140

**Comment by spekulatius** [comment]
maintenance module should be good now @unclecheese: https://github.com/bringyourownideas/silverstripe-maintenance/pull/141

**Comment by unclecheese** [comment]
Yay, everything is merged! Cheers @spekulatius @nglasl
