### ISSUE TITLE
Existing header links are broken

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/doc.silverstripe.org#224]
I'm seeing this a lot in the change logs docs where the page hierarchy has changed, although it could be in other places too.

Prior to the new docs page, all anchor links were `/#heading`, where as now it needs to be `/4.x.x/#heading`.

Raising here to ideally programatically fix all anchor links in the change log that are currently broken - otherwise we'll need to just do a run through manually.

See https://docs.silverstripe.org/en/4/changelogs/4.5.0 as an example

**Comment by sminnee** [comment]
I noticed this today on https://docs.silverstripe.org/en/4/changelogs/4.4.0/. 

They go to for example, https://docs.silverstripe.org/en/4/changelogs/#hash-less instead of https://docs.silverstripe.org/en/4/changelogs/4.4.0/#hash-less.

**Comment by unclecheese** [comment]
Pull request: https://github.com/silverstripe/doc.silverstripe.org/pull/226/files
