### ISSUE TITLE
Add documentation on how to add new pages

### ISSUE THREAD

**Issue by bergice** [silverstripe/doc.silverstripe.org#233]
Should include:

* https://github.com/silverstripe/doc.silverstripe.org/blob/master/sources-user.js
* And GitHub action: https://github.com/silverstripe/silverstripe-mfa/commit/03e70007a577ef56c4b2e97bd573437d83585db3

**Comment by GuySartorelli** [comment]
I assume by "new pages" it really means "new modules to the userhelp docs" - and that's easy enough to figure out by looking at the code. We won't be spending time to add this documentation.
