### ISSUE TITLE
Mailto link do not work

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/doc.silverstripe.org#235]
If you look at this article in tho doc, you'll notice that the email link is actually rendered as a regular link: https://docs.silverstripe.org/en/4/contributing/issues_and_bugs/#reporting-security-issues

`[security@silverstripe.org](mailto:security@silverstripe.org)` in Markdown points to `https://docs.silverstripe.org/en/4/contributing/mailto:security@silverstripe.org/`

PRs
- https://github.com/silverstripe/doc.silverstripe.org/pull/240

**Comment by dhensby** [comment]
I *think* email addresses should just be auto-linked as is, so that link style can just be taken out

**Comment by GuySartorelli** [comment]
Created a PR for this - we could go and update the docs to not use links, but someone can just as easily add one in the future and then we're stuck back in the same situation. May as well just fix it outright.
