### ISSUE TITLE
The SS4 userhelp as a bunch of "userguide" instead of the actual title

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/doc.silverstripe.org#246]
A bunch of module with userhelp are missing the meta data data for the page title. The missing titles are there in the SS3 doc.

![image](https://user-images.githubusercontent.com/1168676/185736171-bb5c5664-c6d9-4654-9ae1-c493522f2b63.png)

## Pull requests
- https://github.com/silverstripe/silverstripe-blog/pull/684
- https://github.com/silverstripe/silverstripe-ckan-registry/pull/273
- https://github.com/silverstripe/silverstripe-elemental/pull/999
- https://github.com/silverstripe/silverstripe-contentreview/pull/169
- https://github.com/silverstripe/silverstripe-documentconverter/pull/33
- https://github.com/silverstripe/silverstripe-userforms/pull/1163
- https://github.com/silverstripe/silverstripe-iframe/pull/61
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/180
- https://github.com/silverstripe/silverstripe-mfa/pull/464
- https://github.com/silverstripe/silverstripe-registry/pull/71
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/468
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/175
- https://github.com/silverstripe/silverstripe-versionfeed/pull/73
- https://github.com/silverstripe/silverstripe-taxonomy/pull/82
- https://github.com/silverstripe/silverstripe-subsites/pull/485

## Github actions PRs
- https://github.com/silverstripe/silverstripe-elemental/pull/1000
- https://github.com/silverstripe/silverstripe-userhelp-content/pull/176
- https://github.com/silverstripe/silverstripe-subsites/pull/486
- https://github.com/silverstripe/silverstripe-taxonomy/pull/83
- https://github.com/silverstripe/silverstripe-versionfeed/pull/74
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/176
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/469
- https://github.com/silverstripe/silverstripe-registry/pull/72
- https://github.com/silverstripe/silverstripe-mfa/pull/466
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/181
- https://github.com/silverstripe/silverstripe-iframe/pull/62
- https://github.com/silverstripe/silverstripe-userforms/pull/1164
- https://github.com/silverstripe/silverstripe-documentconverter/pull/34
- https://github.com/silverstripe/silverstripe-contentreview/pull/170
- https://github.com/silverstripe/silverstripe-ckan-registry/pull/274
- https://github.com/silverstripe/silverstripe-blog/pull/686

**Comment by GuySartorelli** [comment]
userhelp.silverstripe.org has no updated after merging the PRs.
I tried to do it manually but it looks like the hook I have information for is explicitly only for docs.silverstripe.org

The webhooks for these repositories appear to have branch filters which are not set to the correct branches for CMS 4 userhelp PRs, which means the action will never fire when PRs for CMS 4 userhelp on these modules are merged.

We need to update the hooks these modules to include the CMS 4 branches.

**Comment by GuySartorelli** [comment]
Through trial and error I was able to find the netlify deploy status page for userhelp: https://app.netlify.com/sites/ss-userhelp/deploys
We should probably link to this from the https://github.com/silverstripe/doc.silverstripe.org readme (next to the one for the dev docs site)

**Comment by maxime-rainville** [comment]
Merged all the PR except blog. Opened a service desk request to try to regain access to netlify.

**Comment by maxime-rainville** [comment]
All done
