### ISSUE TITLE
Advanced templates page redirect?

### ISSUE THREAD

**Issue by sergeseva** [silverstripe/doc.silverstripe.org#25]
Advanced templates documentation page

http://doc.silverstripe.com/framework/en/3.0/reference/advanced-templates

foir ss versions v3.0 v3.1 needs to be updated / have a redirect. Other pages in Reference module may need to be revised, too, for v3.0 v3.1.

**Comment by camfindlay** [comment]
@SpiritLevel take it you'll address this one in your rewrites

**Comment by SpiritLevel** [comment]
Yip :)
