### ISSUE TITLE
Docs will not build correctly for CMS 5 docs with 5.0 branch

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/doc.silverstripe.org#257]
For some reason, when changing the branch that docs looks at from `5` to `5.0` the preview shows that all routes for v5 docs are broken.

See the PR https://github.com/silverstripe/doc.silverstripe.org/pull/256 and its preview https://deploy-preview-256--ss-docs.netlify.app/

## Acceptance criteria
- [x] Targetting at the `5.0` branch correctly fetched docs from that branch

## PRs
- https://github.com/silverstripe/doc.silverstripe.org/pull/255

**Comment by emteknetnz** [comment]
Duplicate https://github.com/silverstripeltd/product-issues/issues/698

**Comment by emteknetnz** [comment]
Linked PR has been merged
