### ISSUE TITLE
Problems with developer docs - irrelevant results (especially when searching non-default docs)

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/doc.silverstripe.org#259]
There are several problems with the search in developer docs right now:
1. If you are searching on v3 or v5 docs, it only gives you results for v4 docs (meaning you sometimes don't get relevant results, and you are always redirected to v4 docs which may not be the same as the docs for the version you were looking for)

## Acceptance criteria
- When searching, you only get results for the version you are currently viewing.
- There's doc on how to configure new search for new major releases.
- Create a a follow card for UserHelp

## Note
- We recently upgraded to Algolia docSearch v3. The search option dashboard there as a lot of new options. There could be some magical fix there.
- The following doc may be useful:
    - [Introduce global information as meta tags](https://docsearch.algolia.com/docs/required-configuration/#introduce-global-information-as-meta-tags)
    - [Indexing content for faceting](https://docsearch.algolia.com/docs/record-extractor/#indexing-content-for-faceting)
    - [Avoid duplicates by promoting unicity](https://docsearch.algolia.com/docs/tips/#avoid-duplicates-by-promoting-unicity) (aka use facets to search a specific version of docs)
    - [Filtering your search](https://docsearch.algolia.com/docs/docsearch-v3/#filtering-your-search) (again, using facets)
    - [Migrating from the legacy scraper](https://docsearch.algolia.com/docs/migrating-from-legacy/)

## PRs
- https://github.com/silverstripe/doc.silverstripe.org/pull/262

**Comment by maxime-rainville** [comment]
When we hit stable, we'll probably want to make the 5 branch the default branch. Probably as part of that process, the 5 branch will become what is being indexed by search results.

**Comment by GuySartorelli** [comment]
In that case we'll still have the same problem - it'll just be different branches that exhibit the problem.

**Comment by maxime-rainville** [comment]
I've put in a separate request for the User Help.

**Comment by maxime-rainville** [comment]
Still waiting for Algolia for userhelp. We should proceed with the developer doc deployment because this is a blocker for the CMS5 release.

**Comment by GuySartorelli** [comment]
I've made a new separate card to handle the userhelp changes: https://github.com/silverstripe/doc.silverstripe.org/issues/263

**Comment by GuySartorelli** [comment]
PR merged and dev docs search is working as expected. New card created for userhelp.
