### ISSUE TITLE
Migrate to the latest version of Algolia for search

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/doc.silverstripe.org#260]
The search uses [Algolia Doc Search](https://docsearch.algolia.com/). They have migrated to  new version however, which requires us to upgrade our set up.

## Acceptance criteria
- [x] Apply for the new Algolia Doc Search.
- [x] Doc site is updated to use the new Algolia Doc Search
- [x] Our [internal doc is updated](https://silverstripe.atlassian.net/wiki/spaces/SSDOC/overview#Search) to reflect the new set up
- [x] Search is functional

## Note
While doing this, keep https://github.com/silverstripe/doc.silverstripe.org/issues/259 in kind.

**Comment by maxime-rainville** [comment]
I requested the doc search account and added all members of the CMS Squad to our account.

The search started working again immediately without me needing to do anything. I think it must have read the settings from our old account.

**Comment by maxime-rainville** [comment]
I've updated our internal doc. The new interfaces seems to have a lot of bells and whistles that I don't have a lot of time to review right now.

The User Help doc seems to be working fine as well.

I'm going to call this done, but we might want to have a follow up look to make sure the CMS3, CMS4 and CMS 5 branches are all indexed properly.

**Comment by GuySartorelli** [comment]
Spoiler alert: Only CMS 4 is indexed. It hasn't indexed CMS 3 or 5 docs at all. But that can be handled separately under #259
