### ISSUE TITLE
userhelp algolia index needs to be updated

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/doc.silverstripe.org#263]
Userhelp is still using an old search index. After #259 search is completely broken as a result. We need to update it, the same as we did for developer docs.

We have a request in with algolia to get an app set up for us - once this is set up, we need to update the crawler script (probably just duplicate the script ss-docs is using) and and index settings as appropriate.

We also will need to update the environment variables in netlify.

**Comment by maxime-rainville** [comment]
I haven't received a reply from Algolia in weeks. I think they are not to incline in directly supporting people on the free plan.

**Comment by maxime-rainville** [comment]
Accaount has been set up and all the CMS Squad has been added.

**Comment by GuySartorelli** [comment]
Userhelp search is now updated to use the new algolia index and should produce correct results based on which version you're searching against

**Comment by emteknetnz** [comment]
Seems to work well
