### ISSUE TITLE
Remove search on UserHelp

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/doc.silverstripe.org#267]
Following https://github.com/silverstripe/doc.silverstripe.org/issues/263, we've decided to remove search from UserHelp.

## Acceptance criteria
- Search is off on UserHelp
- Search is on on Developer doc
 
## Note
- We will potentiall move the doc to a new place in the process of rebuilding silverstripe.org. Keep that in mind while fixing the doc.

**Comment by GuySartorelli** [comment]
This isn't happening anymore, since algolia ended up setting us up an application for it.
