### ISSUE TITLE
Move GraphQL docs to be added as optional module in CMS 6

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/doc.silverstripe.org#304]
When we have CMS 6 docs, include the silverstripe/graphql module as an optional module, similar to linkfield

## Acceptance Criteria
- [ ] silverstripe/silverstripe-graphql is added to https://github.com/silverstripe/doc.silverstripe.org/blob/master/sources-docs.js and displays in the "Optional Features" section

## PRs
- https://github.com/silverstripe/silverstripe-graphql/pull/604
- https://github.com/silverstripe/doc.silverstripe.org/pull/310

**Comment by GuySartorelli** [comment]
PRs merged
