### ISSUE TITLE
Smooth scrolling causes a poor experience

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/doc.silverstripe.org#319]
### Module version(s) affected

master

### Description

On long pages (For a great example, click on "full commits list" on https://docs.silverstripe.org/en/5/changelogs/5.0.0) it takes _forever_ to scroll to the right place.

It's also not great for accessibility, and adds more JS for little benefit.

### How to reproduce

Click on "full commits list" on https://docs.silverstripe.org/en/5/changelogs/5.0.0. Wait.

### Possible Solution

Remove smooth-scroll package and configuration

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
PR merged. Will be auto-deployed.
