### ISSUE TITLE
Hints don't parse markdown

### ISSUE THREAD

**Issue by dhensby** [silverstripe/doc.silverstripe.org#40]
See http://doc.silverstripe.org/framework/en/3.0/topics/i18n#usage-in-template-files

Where the hint box has a link to 2.4 docs but it is showing as raw markdown

**Comment by camfindlay** [comment]
cheers, possible this is a bug in docsviewer module?

**Comment by wilr** [comment]
Thats also on the older version of the module. Should be resolved on the latest docsviewer and new documentation.

**Comment by dhensby** [comment]
Ah great, cheers.
