### ISSUE TITLE
Different visual style for links that are API references.

### ISSUE THREAD

**Issue by wilr** [silverstripe/doc.silverstripe.org#46]

**Comment by unclecheese** [comment]
@silverstripe/designers Can you advise on this, please? I've just classed the link as `api-link`. Just need an idea for style.

**Comment by clarkepaul** [comment]
Was there a pattern we used on the old doc site?

**Comment by sachajudd** [comment]
I don't think there was any original styling for api-links in the old docs site. All external links I'd suggest have an icon to let users know you'll be directed to a new tab. Could we use this styling for both external links and api-links?

**Comment by unclecheese** [comment]
![Screenshot 2019-11-20 10 13 05](https://user-images.githubusercontent.com/654636/69187087-be04ec80-0b7e-11ea-9eaf-bde460d04572.png)
I went with this. OK?

I think API links deserve special treatment over regular external links. I'd also like to tooltip them at some point to show the summary of the API reference.

**Comment by clarkepaul** [comment]
Makes a lot more sense with the tooltip as that is how the dotted/dashed line is typically used.

**Comment by unclecheese** [comment]
Have reverted to standard `text-decoration: underline` for now, and if we get tooltips working, we'll switch it.
