### ISSUE TITLE
Top 50 404 errors

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/doc.silverstripe.org#50]
These are the current top 50 404 crawl errors from Google Webmaster Tools, will need to map these to appropriate places. The update in #49 should correct some of these, the rest may need to be added to the htaccess. I'll update this list as I see crawl fixes after deploying the new htaccess file.

Some are for really old versions of the docs which we do not serve up anymore (2.3), we'll need a place for these to redirect to (either to 2.4 docs, or perhaps the docs folder in github?).

The following is in order of most requested 404s:

404 http://docs.silverstripe.org/changelog
404 http://docs.silverstripe.org/installation-into-subversion
404 http://docs.silverstripe.org/modules:rssaggregator
404 http://docs.silverstripe.org/memberauthenticator
404 http://docs.silverstripe.org/modules:mssql
404 http://docs.silverstripe.org/authenticator
404 http://docs.silverstripe.org/recipes:combining_files
404 http://docs.silverstripe.org/datefield
404 http://docs.silverstripe.org/member
404 http://docs.silverstripe.org/en/topics/datamodel/
404 http://docs.silverstripe.org/treedropdownfield
404 http://docs.silverstripe.org/en/2.4/tutorials/1-building-a-basic-site/
404 http://docs.silverstripe.org/en/topics/security/
404 http://docs.silverstripe.org/en/topics/environment-management/
404 http://docs.silverstripe.org/en/topics/testing/
404 http://docs.silverstripe.org/en/2.4/tutorials/2-extending-a-basic-site/
404 http://docs.silverstripe.org/en/topics/configuration/
404 http://docs.silverstripe.org/download
404 http://docs.silverstripe.org/en/reference/permission/
404 http://docs.silverstripe.org/en/topics/controller/
404 http://docs.silverstripe.org/typography
404 http://docs.silverstripe.org/en/howto/
404 http://docs.silverstripe.org/en/topics/rich-text-editing/
404 http://docs.silverstripe.org/en/reference/modeladmin/
404 http://docs.silverstripe.org/en/3.0/tutorials/5-dataobject-relationship-management/
404 http://docs.silverstripe.org/en/2.4/tutorials/5-dataobject-relationship-management/
404 http://docs.silverstripe.org/en/2.4/tutorials/3-forms/
404 http://docs.silverstripe.org/en/3.0/tutorials/2-extending-a-basic-site/
404 http://docs.silverstripe.org/en/2.4/topics/reference/requirements/
404 http://docs.silverstripe.org/en/3.0/tutorials/1-building-a-basic-site/
404 http://docs.silverstripe.org/modules:auth_ext_drivers
404 http://docs.silverstripe.org/en/reference/built-in-page-controls
404 http://docs.silverstripe.org/en/misc/release-process/
404 http://docs.silverstripe.org/en/trunk/developer_guides/model
404 http://docs.silverstripe.org/en/reference/dataextension/
404 http://docs.silverstripe.org/en/developer_guides/data_types_and_casting/
404 http://docs.silverstripe.org/en/getting_started/installation/composer/
404 http://docs.silverstripe.org/en/upgrading/release%20process/
404 http://docs.silverstripe.org/en/3.0/tutorials/4-site-search/
404 http://docs.silverstripe.org/en/4.0/reference/grid-field/
404 http://docs.silverstripe.org/en/2.4/tutorials/4-site-search/
404 http://docs.silverstripe.org/en/developer_guides/customising_the_admin_interface/reference/cms-architecture/
404 http://docs.silverstripe.org/en/developer_guides/forms/fields/common_subclasses/
404 http://docs.silverstripe.org/tabset
404 http://docs.silverstripe.org/en/trunk/developer_guides/extending/extensions
404 http://docs.silverstripe.org/en/topics/css/
404 http://docs.silverstripe.org/en/developer_guides/customising_the_cms/modeladmin/
404 http://docs.silverstripe.org/en/developer_guides/model/sqlquery
404 http://docs.silverstripe.org/en/installation/upgrading/
404 http://docs.silverstripe.org/en/developer_guides/data_model_and_orm/

**Comment by SpiritLevel** [comment]
@camfindlay Hi Cam. On http://www.silverstripe.org/learn/, second paragraph under Developer Learning,  the link to developer documentation is to domain doc.silverstripe.com but this gets re-directed to docs.silverstripe.org. All the 404s above are also to doc not docs. Should all these be rewritten to an appropriate place on docs.silverstripe.org and PRs made on the 3.1 branch ?

**Comment by camfindlay** [comment]
the canonical for docs site is "docs.silverstripe.org" now, this wasn't always the case in the past. We made a call to go with "docs" after some discussion in IRC.

doc.silverstripe.org has rewrites in place already I believe to rewrite to docs.

the main thing to worry about is the slugs after the domain name. eg /upgrading:2.4.0
and finding an appropriate place to redirect them to in the new docs. A lot of them are legacy. Note the docs before 3.1remain in their legacy structure it was decided to apply the new IA from 3.1 docs forward.

**Comment by camfindlay** [comment]
@SpiritLevel I may go get an updated top 50 404 errors list.

**Comment by SpiritLevel** [comment]
@camfindlay Good idea. Just looking at rewrite rules in doc.silverstripe.org/.htaccess  and the 2.4 docs.

How do you want to handle 2.3 docs ?

**Comment by camfindlay** [comment]
I'm just confirming which of the top 50 are still 404s and I'll replace the above list soon.

**Comment by camfindlay** [comment]
Updated the list above. Hold off any 2.3 docs stuff until we make a call on this (we don't serve these docs up anyway).

**Comment by SpiritLevel** [comment]
OK. 2.4 and up only. Can you show me how you want this done, say, for the first one:

http://doc.silverstripe.org/upgrading:2.4.0 

which looks like it should get mapped to 

http://docs.silverstripe.org/en/2.4/installation/upgrading/

**Comment by SpiritLevel** [comment]
OK...list has changed. So, let's use the new top one as an example:

http://docs.silverstripe.org/changelog

which I assume should map to

http://docs.silverstripe.org/en/3.1/changelogs/

**Comment by camfindlay** [comment]
Looks good to me, have you done rewrite rules in htaccess before?
I'd imagine you create a PR with your rules and we can peer review it our end and offer any suggested fixes.

It would be something like this (though you might need to investigate escaping the : 
RewriteRule ^changelog/?$ /en/changelogs [R=301,L]

If you dont include a version number it pushes to the current stable at the time in this case makes sense as the incoming URL is quite general

**Comment by SpiritLevel** [comment]
OK. Got it. I'll double check the syntax. Yes, I have played with .htaccess rules before. 

Just to confirm: you want URLs with no version number to get mapped to one with 301 ?

**Comment by SpiritLevel** [comment]
At bottom of http://www.silverstripe.org/community/contributing-to-silverstripe/ the link to developer documentation should be changed to point to docs.silverstripe.org/..... :)

**Comment by SpiritLevel** [comment]
What about changing https://github.com/silverstripe/doc.silverstripe.org to https://github.com/silverstripe/docs.silverstripe.org for consistency ?

**Comment by SpiritLevel** [comment]
http://www.silverstripe.org/learn/ in section developer learning also has links to doc.silverstripe.org rather than to docs.silverstripe.org, both in the paragraph and in the menu on the right.

**Comment by camfindlay** [comment]
I think fixing the rewrites has higher priority than changing the project repo name ;) We can do house keeping when we have a stable house.

**Comment by SpiritLevel** [comment]
At http://www.silverstripe.org/software/download/ in useful links at bottom left: the video mentions nothing about git. The video discusses installing SS with composer (and the satisfying of version constraints), using _ss_environment.php, and running the SS web installer.

**Comment by camfindlay** [comment]
@SpiritLevel you'd probably be better logging these things in the user feedback tab on ss.org site. 

Let's keep this dialogue here specific to the rewrites for the docs site.

**Comment by SpiritLevel** [comment]
@camfindlay  Sorry. I'd change them myself but I don't believe I can submit a PR for those. I'll move them, then delete them :) 

Not sure where to rewrite http://docs.silverstripe.org/modules:rssaggregator to.

Maybe to http://docs.silverstripe.org/en/3.1/developer_guides/integration/how_tos/embed_rss/ ?

**Comment by SpiritLevel** [comment]
@camfindlay More questions!

What to do with http://docs.silverstripe.org/memberauthenticator  ?

http://api.silverstripe.org/2.4/class-MemberAuthenticator.html ?
http://api.silverstripe.org/3.0/class-MemberAuthenticator.html ?
http://api.silverstripe.org/3.1/class-MemberAuthenticator.html ?
http://api.silverstripe.org/3.2/class-MemberAuthenticator.html ?

For these URLs, we cannot omit the 2.4,...,3.2. The URL http://api.silverstripe.org/class-MemberAuthenticator.html is not found (and there is no nice 404 error page) It would be nice if this URL would take you to the current stable version of the api docs for MemberAuthenticator; maybe this would be a good idea ?

**Comment by camfindlay** [comment]
Perhaps any that you cannot find a suitable place just direct to the home page of docs.

**Comment by camfindlay** [comment]
Any redirects that don't include a version number, make sure the destination also doesn't include a version number.

**Comment by SpiritLevel** [comment]
OK. There are quite a few that refer to the api, like MemberAuthenticator above, and it appears we have to specify a version in the target.

**Comment by camfindlay** [comment]
Do your best, the Pull Request is when we can review and get input from others.

**Comment by camfindlay** [comment]
@SpiritLevel how have you got on getting a local copy of the site working to test your rewrites.

**Comment by SpiritLevel** [comment]
@camfindlay Just set up local test instance of doc.silverstripe.org now and the site is working :) Will do testing. Then I'll submit pull request.

**Comment by camfindlay** [comment]
#65
