### ISSUE TITLE
Changelog Version order is confusing - looks incorrect

### ISSUE THREAD

**Issue by LukePercy** [silverstripe/doc.silverstripe.org#52]
Hey Guys,

The versioning order on http://doc.silverstripe.org/en/changelogs/ doesn't look right.
3.1.12 is the latest to my understanding (then RC,Alpha,Beta etc.), but the ordering on that list puts it below 3.1.9 this can be confusing to clients when reading what version is the latest. 

Thanks,
Luke.

**Comment by camfindlay** [comment]
@LukePercy think this might actually be a docsviewer module issue I've opened this over at https://github.com/silverstripe/silverstripe-docsviewer/issues/68
