### ISSUE TITLE
Rewrite issues on /en/3.1/getting_started/installation/

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/doc.silverstripe.org#66]
@SpiritLevel deployed rewrites to live, this caused some issues so have rolled back until we get a fix.

The issue spotted is http://docs.silverstripe.org/en/3.1/getting_started/installation/ gets caught in a loop.

You end up at: http://docs.silverstripe.org/en/3.1/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/getting_started/installation/

Please review the current rewrites and see if you can find the cause and fix :)

**Comment by SpiritLevel** [comment]
@camfindlay Why don't our dev versions have this problem ? Any idea ? Should be easy enough to fix :)

**Comment by camfindlay** [comment]
Suspect it is:

	RewriteRule ^(.*)/installation/?$ /$1/getting_started/installation [R=301,L]

I don't think we had that rule before or we had a more restricted match

**Comment by camfindlay** [comment]
I can confirm my local dev has this issue

**Comment by camfindlay** [comment]
the rule matches itself once it's redirected.

**Comment by camfindlay** [comment]
This the fix is to replace 
	RewriteRule ^(.*)/installation/?$ /$1/getting_started/installation [R=301,L]

with

RewriteRule ^([a-z]{2})/installation/?$ /$1/getting_started/installation [R=301,L]

**Comment by SpiritLevel** [comment]
Strange I didn't see it on mine :\

**Comment by camfindlay** [comment]
Try out test server http://beta.docs.silverstripe.org/en/3.1/getting_started/installation

**Comment by SpiritLevel** [comment]
Can close this :)

**Comment by camfindlay** [comment]
I'll close once we get on the live server.
