### ISSUE TITLE
Home menu item always goes to 3.2 even when in another version.

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/doc.silverstripe.org#79]

**Comment by camfindlay** [comment]
This might actually be a bug in https://github.com/silverstripe/silverstripe-docsviewer can you raise it there.

**Comment by SpiritLevel** [comment]
How about I first collect a few of the obvious usage issues here. Then, I'll track down the source and raise the issues elsewhere if needed :)

**Comment by tractorcow** [comment]
Is there a .htaccess rewrite?

**Comment by SpiritLevel** [comment]
Will look into this @tractorcow at the same time as #75 #71 #25.

**Comment by tractorcow** [comment]
Actually, I think the "home" button should be rewritten to include the current version of the docs. E.g. https://docs.silverstripe.org/en/3.2/ instead of https://docs.silverstripe.org/. Given that the home menu is at a lower level than the version selector.

**Comment by SpiritLevel** [comment]
I totally agree :) It is also then consistent with the other menu items under "home".
