### ISSUE TITLE
Include link to Github docs on custom Nginx 500 error page to help people find docs

### ISSUE THREAD

**Issue by wilr** [silverstripe/doc.silverstripe.org#8]
Suggestion via http://www.silverstripe.org/blog-module-forum/show/20796#post316653. 

We have the benefit of the documentation being distributed, just need to communicate that if a server error. Won't help if it's a DNS or hardware fault though.

**Comment by camfindlay** [comment]
@wilr would this require us making a static html page and then getting nginx error page setup to point to this on a 500?
