### ISSUE TITLE
Page.ss has php code in it on framework page ?

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/doc.silverstripe.org#82]
Not sure where to put this minor issue so sticking it here as something I noticed...feel free to close.

On http://www.silverstripe.org/software/framework/ there is a screen shot with Page.ss in an editor but it contains php. The pedant in me balks at this! But, the business person in me appreciates the desire to use the "ss" extension for marketing purposes. Would it not be better to have an interesting template for Page.ss displayed instead of the Page type/controller definition in php ?

**Comment by jonom** [comment]
Haha good catch! @camfindlay @unclecheese think this is the result of the code competition you ran is this something you can help with?

**Comment by dhensby** [comment]
@camfindlay

**Comment by camfindlay** [comment]
Cheers. The php is correct, the file name here is not. Good catch. Anyone want to do a quick photoshop job and send me the result? :trollface:
