### ISSUE TITLE
favicons should be in themes/docs/favicons not web root

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/doc.silverstripe.org#90]
It would be cleaner to put all favicons into a separate folder themes/docs/favicons and update the links to the favicons in Includes/DocumentationHead.ss

**Comment by tractorcow** [comment]
Some web browsers will assume a web-root favicon.ico. Could it be in both locations?

**Comment by SpiritLevel** [comment]
Oh. Wouldn't the links in <head>...</head> force any browser to look where you want it to for favicon.ico and all the others ?

**Comment by SpiritLevel** [comment]
Which browsers do that ?!

**Comment by SpiritLevel** [comment]
@tractorcow Seems like it is OK across all browsers to use this:

&lt; link rel="shortcut icon"  href="http://example.com/myicon.ico" &gt;

See https://en.wikipedia.org/wiki/Favicon#Use_of_favicon

Not sure about mobile browsers.

**Comment by tractorcow** [comment]
I think it's probably ok as long as you have the `<link >` element. :) You're right.

**Comment by SpiritLevel** [comment]
I think having png versions for mobile devices is sufficient:

https://css-tricks.com/favicon-quiz/

If nobody has any objections, I'd like to clean up the favicons per OP.

**Comment by mandrew** [comment]
Removing the favicon from root won't stop any traffic from still trying to hit it though.
https://perishablepress.com/block-favicon-url-404-requests/
https://perishablepress.com/redirect-all-requests-for-a-nonexistent-file-to-the-actual-file/

If it is just to be cleaner then I'd argue if it is really necessary? If this change is done for docs then it would also be done for api, ss.org, addons etc.

Also be tested via http://realfavicongenerator.net/

**Comment by SpiritLevel** [comment]
@mandrew Thanks for those references :) 

I suppose one could leave favicon.ico in the root and put the rest in a folder. But, I have read that the .ico format is on its way out. Why not give it the boot ?

Cleanliness is next to Godliness! :P Seriously, though, it is nice to have a really tidy file system, especially in the root folder, with "noise" relegated to subfolders. So, while not necessary, I think wherever it is possible to be tidy, one should try to do so, since this encourages tidiness generally. Redirecting seems easy enough. I'd be happy to make the changes on here and anywhere I am able to. Anyhow, it certainly isn't much work to implement this, and I think the tidiness gained outweighs the work, but that is just my opinion :)

**Comment by mandrew** [comment]
I think that the article does raise a good point that that spiders and other browsers might not realise that it's on the way out and still hit the server. 

Happy for the other files to be moved but I'd either leave the favicon in the main directory or look into implementing the url redirect as per the article.

**Comment by SpiritLevel** [comment]
Yes, and I suppose also that there is little we can do to discourage requests for favincon.ico in the root.  

My preference is for related things to be in one place so I'd be inclined to put all favicons in a subfolder and then put in a redirect for those beasties that look for favicon.ico in the root :)

**Comment by SpiritLevel** [comment]
@mandrew I couldn't see anything to be done for api.silverstripe.org favicons but I did do userhelp, addons, and docs.  Someone "on the inside" will have to do www.silverstripe.org, if these changes are considered desirable.

**Comment by dhensby** [comment]
FYI: Browsers will always look at /favicon.ico as their default. If it's defined in the HTML then they probably won't but it's a terrible hang-over convention where browsers look for a particular file.

This can be a problem in SS if it causes 404s so it either has to 301 or just have a file there anyway.

**Comment by mandrew** [comment]
@SpiritLevel I'd agree with @dhensby, can we just leave the favicon.ico at the root of the website?

**Comment by SpiritLevel** [comment]
Hey @mandrew 

Oh, from your comment above, I thought you were happy with moving favicon.ico out of root as long as a redirect was put in place, which has been done. Aren't legacy issues like this best handled via redirects ?  Besides, @dhensby merged it...and, it couldn't possibly be the case that he would perform a sneaky merge :P 

Is there a particular reason for wanting to keep favicon.ico in the root ? It is so much cleaner to put all that bumpf in its own folder, out of the way.

**Comment by mandrew** [comment]
@SpiritLevel if @dhensby has merged it then thats ok : ) Would be good to monitor the 404s on docs just to confirm all is well

**Comment by SpiritLevel** [comment]
@mandrew I think I'll try to sort out some other rewrite rules as well so will definitely watch out for those 404s :) Let me know if you notice any.

**Comment by dhensby** [comment]
I merged it because I saw the 301 was handling requests to root favicon.ico so I determined it shouldn't block merge.

If the consensus is it should go back into webroot, I'd accept that too.

**Comment by dhensby** [comment]
OK, I think one point that I've noticed is sub-optimal is that the 301 for favicon.ico requires the .htaccess to have some inherent knowledge about the current theme; which I think is too tightly coupled. 

That'd be my argument for keeping an icon in the root.

**Comment by SpiritLevel** [comment]
Interesting issue...I suppose an .htaccess file with rewrite rules will always be inherently coupled with a site's directory structure. No way to avoid it; one can only minimise coupling by clever use of regexs to reduce explicitly including a lot of path information. Hence, whenever there is a change to a site's directory structure, one has no choice but to review the .htaccess rewrite rules. I guess such a review falls into the category of "standard operating procedure".

Rewrite rule references to the current theme, as seen in the favicon 301, introduces a level of coupling that would be only be a problem if one wants to change an existing theme's folder structure or if one wants to create a new theme and switch to it. Coupling only becomes a problem if you try to separate things.

Firstly, my guess is that there won't be frequent changes to the theme structure for doc.silverstripe.org. Secondly, even if changes were made, one would then just follow "standard operating procedure" and review the rewrite rules. Thirdly, only a single rewrite rule would be affected, if at all. So, I would argue that the coupling is not too terribly tight.

So, here are the two options:

Option 1: No favicons in root and one extra rewrite rule. Slighly increased coupling and hence maintenance is the cost. The benefit is all favicons in a single, logical place, off of the main stage. 

Option 2: No extra rewrite rule and only the single file favicon.ico in the root. No new coupling and one less rewrite rule to worry about are the benefits, as well as a minor performance gain. The cost is having favicon.ico on the main stage. 

I have come to appreciate that dealing with rewrite rules is a pain; they are hard to get right and so should be avoided whenever possible. It is easy to avoid them here and so I have just convinced myself that Option 2 is better! Sorry for the about-face!

**Comment by camfindlay** [comment]
+1 for option 2... favicon in root has been around a while, it works.

**Comment by dhensby** [comment]
yes, option 2 is best IMO.

You've convinced yourself option 2 is best, but I'll address your preface:

You're justifying tight coupling with a lot of common misplaced justifications. You're saying "oh, changing the rules will be SOP" but the point is loose coupling is to prevent the cascade of changes having to be part of SOP because it's just so likely to be missed.

1. It's not documented anywhere
2. If it was, it probably wouldn't be read by the person making changes in the future

Also, just because we can't easily identify the need *now* for loose coupling, doesn't mean it won't happen later.

Granted, this is a trivial example that, on balance, we could probably leave tightly coupled, but it's still an approach that we need to be mindful of with all coupling of knowledge.

Ultimately, our `.htaccess` shouldn't need to have knowledge of the "default" theme.

**Comment by SpiritLevel** [comment]
Thanks @dhensby for taking the time to reply :) 

I like trivial examples (like this one) that teach important principles. In this case, the principle is that loose coupling is a design imperative, which I already knew, but have now relearned. Generally, following this imperative will (i) keep SOPs simpler, reducing the chances of making a mistake, and (ii) reduce cascading effects of changes, intentionally made or otherwise. And, more specifically, it requires .htaccess files be kept really lean. On top of this, rewrite rules are hard to get right. So, @camfindlay, all this is seems to be a solid argument for drastically stripping down the rewrite rules in docs.silverstripe.org! OK, enough chit chat from me. Time to sort favicon.ico and tame the rewrite rules :)

**Comment by dhensby** [comment]
@SpiritLevel with re-write rules we are really abusing the `.htaccess` to provide a performant way to redirect users (we intercept requests BEFORE apache hands the request on to PHP).

This is a compromise and we sacrifice loose-coupling for user-experience.

Generally it is fine to do with SS for migrating an old URL structure to a new one as SS typically will redirect for us when URLs change on the site.

eg:

```
/oldurl.asp?id=3 => /about-us/
```

if `/about-us/` is renamed in SS to `/about/` it will be handled without editing the `.htaccess`

**Comment by SpiritLevel** [comment]
Yup. Understood :) A little coupling abuse is OK if it provides huge benefits, involves a very small amount of code, and involves program structure that is highly unlikely to change...for example:

	RewriteRule .* framework/main.php?url=%1 [QSA]
	
I was originally thinking the favicon redirect to a theme folder was of the same ilk but framework/main.php is a much more stable part of SS than the theme choice!
