### ISSUE TITLE
Toolbar issues

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/doc.silverstripe.org#93]
~~(1) app/_config/toolbar.yml has settings for GlobalNav that do not work for a local install of doc.silverstripe.org. In particular, the dev and test hostnames are set for silverstripe servers. This causes a 404 when attempting to load toolbar.min.css. I feel that doc.silverstripe.org should run anywhere it is installed, not just on the ss servers :)~~

(2) toolbar/css/toolbar.css is empty

~~(3) locally installing toolbar.min.css (downloaded from docs.silverstripe.org) and changing toolbar.yml eliminates the 404 but does not result in toolbar functioning; one still gets a big js "X". Have not yet fully tracked down the problem.~~

(4) some margin-bottom is needed for toolbar on the http://docs.silverstripe.org site when viewing on small devices (page title is too close to toolbar). And, toolbar doesn't collapse properly on small devices.

**Comment by camfindlay** [comment]
This seems more like an issue with the module https://github.com/silverstripe/silverstripe-globaltoolbar (this is what is used across all the community subdomain sites).

**Comment by SpiritLevel** [comment]
Visually, the toolbar is fully responsive on 

http://www.silverstripe.org/community/ 
http://www.silverstripe.org/learn/

for example, and appears to work just fine. But the toolbar stumbles on 

https://userhelp.silverstripe.org
https://docs.silverstripe.org
http://api.silverstripe.org/

and one gets that 404 and "X" when installing them locally. This suggests it is not necessarily the toolbar module, but instead might be docsviewer...it is probably something obvious...I had a look but couldn't see anything.

**Comment by camfindlay** [comment]
On www.silverstripe.org the toolbar is internally generated. On the other sites it is not.  

![](http://cdn.meme.am/instances/250x250/55056957.jpg)

**Comment by SpiritLevel** [comment]
Can we just move how it is generated on www.silverstripe.org over to userhelp, docs, api ? Might as well have the same setup, if possible. Suggestions ?

**Comment by mandrew** [comment]
@SpiritLevel that is the plan but docs/userhelp run on a different version of bootstrap and api is a totally different kettle of fish as all the templates are automatically generated and don't use bootstrap at all, so a decent amount of work will be needed to get the same toolbar styling to work on all the separate sites.

**Comment by SpiritLevel** [comment]
@mandrew Ah, OK. Thanks. I'll just turn the toolbar off on my local repos then.

**Comment by camfindlay** [comment]
@SpiritLevel toolbar generates some static files that subdomains pull from silverstripe.org. You can probably change your toolbar.yml to point to there to see the toolbar working locally.
